import React from "react";
import "./globals.css";
import { CartProvider } from "./cart-context";
import NavBar from "./components/NavBar";

export const metadata = {
  title: "My Website",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <NavBar />
          <div className="mx-auto max-w-6xl px-4 py-6">{children}</div>
        </CartProvider>
      </body>
    </html>
  );
}
